#ifndef MENU_FUELSENSOR_IRREGULARVOLUME_H_INCLUDED
#define MENU_FUELSENSOR_IRREGULARVOLUME_H_INCLUDED

void mFuelSensor_irregular_menu_job(void);
void mFuelSensor_irregular_unitsOfTable_job(void);
void mFuelSensor_irregular_unitsOfTable_lengthUnits_job(void);
void mFuelSensor_irregular_unitsOfTable_volumenUnits_job(void);

void mFuelSensor_irregularVol_newTable_job(void);
void mFuelSensor_irregularVol_newTable_errorConsistency_job(void);
void mFuelSensor_irregularVol_newTable_save_continue_job(void);
void mFuelSensor_irregularVol_newTable_minNode_job(void);
void mFuelSensor_irregularVol_newTable_maximum_size_job(void);

#endif // MENU_FUELSENSOR_IRREGULARVOLUME_H_INCLUDED

